apiVersion: install.alo.dev/v1alpha1
kind: ZeroSDP
metadata:
  labels:
    app.kubernetes.io/name: zerosdp
    app.kubernetes.io/instance: zerosdp-sample
    app.kubernetes.io/part-of: platform-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: platform-operator
  name: zerosdp-sample
spec:
  # TODO(user): Add fields here
