---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - zerosdp.alo.dev
  resources:
  - platforms
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - zerosdp.alo.dev
  resources:
  - platforms/finalizers
  verbs:
  - update
- apiGroups:
  - zerosdp.alo.dev
  resources:
  - platforms/status
  verbs:
  - get
  - patch
  - update
