---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - install.zerosdp.audacioustux.com
  resources:
  - zerosdps
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - install.zerosdp.audacioustux.com
  resources:
  - zerosdps/finalizers
  verbs:
  - update
- apiGroups:
  - install.zerosdp.audacioustux.com
  resources:
  - zerosdps/status
  verbs:
  - get
  - patch
  - update
