# permissions for end users to edit zerosdps.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: zerosdp-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: platform-operator
    app.kubernetes.io/part-of: platform-operator
    app.kubernetes.io/managed-by: kustomize
  name: zerosdp-editor-role
rules:
- apiGroups:
  - install.zerosdp.audacioustux.com
  resources:
  - zerosdps
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - install.zerosdp.audacioustux.com
  resources:
  - zerosdps/status
  verbs:
  - get
